language: python
matrix:
  include:
    - name: "Python 3.7.1 on Linux"
      python: 3.7.1
      language: python
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ] ; then choco install python --version 3.7.5; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ] ; then python -m pip install --upgrade pip ; fi
  - export AMULET_VERSION=$TRAVIS_TAG

install:
  - pip3 install --upgrade pip
  - if [ "$TRAVIS_OS_NAME" = "osx" ] || [ "$TRAVIS_OS_NAME" = "windows" ] ; then pip3 install --user --upgrade setuptools wheel ; else pip3 install --upgrade setuptools wheel ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] || [ "$TRAVIS_OS_NAME" = "windows" ] ; then pip3 install --user -r requirements-dev.txt ; else pip3 install -r requirements-dev.txt ; fi
  - python3 setup.py bdist_wheel || python setup.py bdist_wheel
  - python3 setup.py install || python setup.py install

script:
  - python3 -m unittest discover -v -s tests || python -m unittest discover -v -s tests

notifications:
  email: false